version: '3'

services:

  storehousebd:
    image: postgres
    container_name: storehousebd
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=storehousebd
    volumes:
      #- ${PWD}/StorehouseBD/:/db
      - ${PWD}/StorehouseBD:/docker-entrypoint-initdb.d

  customerbd:
    image: postgres
    container_name: customerbd
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=customerbd
    volumes:
      - ${PWD}/CustomerBD:/docker-entrypoint-initdb.d

  # storehousems:
  #   build: ./StorehouseMS
  #   container_name: storehousems
  #   ports:
  #     - "8040:8040"
  #   depends_on:
  #     - storehousebd

  # customerms:
  #   build: ./CustomerMS
  #   container_name: customerms
  #   ports:
  #     - "8041:8041"
  #   depends_on:
  #     - customerbd
  
  # miniconsole3:
  #   build: ./MiniConsole3
  #   container_name: mini-console3


