version: '3'

services:

  storehousebd:
    image: postgres
    container_name: storehousebd
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=storehousebd
    volumes:
      - ${PWD}/StorehouseBD:/docker-entrypoint-initdb.d

  customerbd:
    image: postgres
    container_name: customerbd
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=customerbd
    volumes:
      - ${PWD}/CustomerBD:/docker-entrypoint-initdb.d

  purchasebd:
    image: postgres
    container_name: purchasebd
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=purchasebd
    volumes:
      - ${PWD}/PurchaseBD:/docker-entrypoint-initdb.d   

  historybd:
    image: postgres
    container_name: historybd
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=historybd
    volumes:
      - ${PWD}/HistoryBD:/docker-entrypoint-initdb.d          

  # apigateway:
  #   build: ./ApiGateway 
  #   container_name: apigateway      
  #   ports:
  #     - "8080:8080"    

  # storehousems:
  #   build: ./StorehouseMS
  #   container_name: storehousems
  #   ports:
  #     - "8040:8040"
  #   depends_on:
  #     - storehousebd  

  # customerms:
  #   build: ./CustomerMS
  #   container_name: customerms
  #   ports:
  #     - "8041:8041"
  #   depends_on:
  #     - customerbd 

  # purchasems:
  #   build: ./PurchaseMS
  #   container_name: purchasems
  #   ports:
  #     - "8042:8042"
  #   depends_on:
  #     - purchasebd
