version: '3'

services:

  storehousebd:
    image: postgres
    container_name: storehousebd
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=storehousebd
    volumes:
      - ${PWD}/StorehouseBD:/docker-entrypoint-initdb.d

  customerbd:
    image: postgres
    container_name: customerbd
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=customerbd
    volumes:
      - ${PWD}/CustomerBD:/docker-entrypoint-initdb.d

  purchasebd:
    image: postgres
    container_name: purchasebd
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=purchasebd
    volumes:
      - ${PWD}/PurchaseBD:/docker-entrypoint-initdb.d    



